table 'Measures Table'
	lineageTag: 892480ef-4bd3-482b-8f47-b4e2df32b4c6

	measure 'Total Item Usage' = ```
			
			ABS ( CALCULATE ( SUM ( f_assembly_build_lines[quantity] ) ) )
			    + ABS ( CALCULATE ( SUM ( f_item_fulfillment_lines[qty] ) ) )
			
			
			```
		formatString: #,0
		lineageTag: 9de24526-2d7a-4dff-b93d-47dfd7f3bc23

	measure Average_Cost = ```
			MAX( 
			    f_ir_lines[item_unit_price]
			)
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d555b33b-2591-4703-af28-53c338375cef

	measure 'Weighted Average' =
			
			[Weighted Average Numerator]/[Item Spend]/100
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: f9224e81-1801-4966-8b4c-2360d1b60cf0

	measure 'Item Spend' = ```
			
			CALCULATE (
			    SUMX (
			        FILTER (
			            dim_item,
			            [Total Item Usage] <> BLANK ()
			                && [Average Cost] <> BLANK ()
			        ),
			        [Total Item Usage] * [Average Cost]
			    )
			)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 4aad9a12-abe6-43ea-a268-106d5e7c7754

	measure 'Average Margin' = ```
			
			VAR TotalSalesPrice =
			    CALCULATE(
			        SUM(f_item_prices_snap[sales_price]),
			        NOT(ISBLANK(f_item_prices_snap[sales_price])),
			        f_item_prices_snap[sales_price] <> 0
			    )
			VAR TotalPurchasePrice =
			    CALCULATE(
			        SUM(f_item_prices_snap[purchase_Price]),
			        NOT(ISBLANK(f_item_prices_snap[purchase_Price]))
			    )
			VAR Difference =
			    TotalSalesPrice - TotalPurchasePrice
			RETURN
			    DIVIDE(Difference, TotalSalesPrice, 0)
			
			```
		formatString: 0%;-0%;0%
		lineageTag: 9db60c10-3f6f-4d47-aa9b-4c1633592004

	measure Quantity = ```
			
			VAR FulfillmentQty = ABS(SUMX(f_item_fulfillment_lines, f_item_fulfillment_lines[qty]))
			VAR AssemblyQuantity = ABS(SUMX(f_assembly_build_lines, f_assembly_build_lines[quantity]))
			VAR CombinedTable =
			    UNION(
			        ROW("SumColumn", "qty", "SumValue", FulfillmentQty),
			        ROW("SumColumn", "quantity", "SumValue", AssemblyQuantity)
			    )
			RETURN
			    SUMX(CombinedTable, [SumValue])
			
			```
		formatString: #,0
		lineageTag: f597011c-75d8-4f48-a6cf-745bdb603018

	measure 'Average Cost' = MAX(f_location_inventory_snap[average_unit_cost])
		lineageTag: a9072894-5ee2-44e7-907a-dcd4a1af38f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Last Purchase Price' = AVERAGEX(f_item_prices_snap,f_item_prices_snap[last_purchase_price])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 88cc0fec-d99d-4d32-902a-04fef789f223

	measure 'Margin Percent' = AVERAGEX(f_item_prices_snap,f_item_prices_snap[margin_pct]/100)
		formatString: 0%;-0%;0%
		lineageTag: 6dc9c4c6-fb60-4f57-8080-e548d503b136

	measure 'Current Margin' = ```
			
			
			VAR TotalSalesPrice =
			    CALCULATE(
			        SUM(f_item_prices_snap[sales_price]),
			        NOT(ISBLANK(f_item_prices_snap[sales_price])),
			        f_item_prices_snap[sales_price] <> 0
			    )
			VAR TotalPurchasePrice =
			    CALCULATE(
			        SUM(f_item_prices_snap[purchase_Price]),
			        NOT(ISBLANK(f_item_prices_snap[purchase_Price])),
			        f_item_prices_snap[purchase_Price] <> 0
			    )
			VAR Difference =
			    TotalSalesPrice - TotalPurchasePrice
			RETURN
			    DIVIDE(Difference, TotalSalesPrice, 0)
			
			
			```
		formatString: 0%;-0%;0%
		lineageTag: 81b43bac-d82d-4cdb-b648-8c4205b2c653

	measure 'Min Sales Margin' = ```
			
			IF(
			    ISBLANK(MAX(f_item_prices_snap[average_cost])),
			    DIVIDE(
			        SUMX(
			            f_item_prices_snap,
			            [Min Sales Price] - [Purchase_Prices]
			        ),
			        SUMX(
			            f_item_prices_snap,
			            [Min Sales Price]
			        )
			    ),
			    DIVIDE(
			        SUMX(
			            f_item_prices_snap,
			            [sales_price] - [average_cost]
			        ),
			        SUMX(
			            f_item_prices_snap,
			            [sales_price]
			        )  
			    )
			)
			
			
			```
		formatString: 0%;-0%;0%
		lineageTag: c4f3cf70-cfb2-4cd9-9a10-4217c7366097

	measure Purchase_Prices =
			
			MAXX(
			    TOPN(
			        1,
			        ADDCOLUMNS(
			            VALUES('f_ir_lines'[item_unit_price]),
			            "@Frequency", CALCULATE(COUNT('f_ir_lines'[item_unit_price]))),
			            [@Frequency],
			            0),
			            'f_ir_lines'[item_unit_price])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b293c102-b208-4f16-96e9-9620b4686dca

	measure 'Min Sales Price' = SUMX(f_item_prices_snap,f_item_prices_snap[sales_price]) * 0.75
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 83c572f3-e36b-42a5-a2bb-c84c448ba20a

	measure 'Current Margin Price' = ```
			
			CALCULATE (
			    SUMX (
			        FILTER (
			            f_item_prices_snap,
			            f_item_prices_snap[sales_price] <> BLANK ()
			                && f_item_prices_snap[purchase_Price] <> BLANK ()
			                && f_item_prices_snap[sales_price] <> 0
			                && f_item_prices_snap[purchase_Price] <> 0
			        ),
			        [Sale Prices] - [Purchase Prices]
			    )
			)
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: e3126abd-0c0f-47ff-8d3d-2005011c7c3d

	measure 'Current Margin Price_' =
			
			CALCULATE(
			    SUMX('f_item_prices_snap', f_item_prices_snap[sales_price] - [Purchase_Prices]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c89fcffe-ee26-4e0c-a62e-4a5a7bbf6aff

	measure 'Purchase Prices' = CALCULATE(SUM(f_item_prices_snap[purchase_Price]))
		lineageTag: e274d6a4-2d4c-43c9-99d1-f80f27eb596c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Weighted Average Numerator' = ```
			
			CALCULATE(
			    SUMX(
			        FILTER(dim_item,[Item Spend] <> BLANK() && [Current Margin Price] <> BLANK()), 
			        [Item Spend] * [Current Margin Price])
			) -- total revenue of the category - total cost of the category / total revenue of the category.
			--total revenue of the category 
			```
		lineageTag: 75e9cc61-5fe2-4408-a163-51a16b6d7dc6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'C Margin' = CALCULATE(SUMX(FILTER(dim_item,[Sale Prices]<>BLANK() && [Purchase Prices]<>BLANK()),[Sale Prices]-[Purchase Prices]))
		lineageTag: ef267367-ed29-44d6-91fd-449b17f9731c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Purchase Price' = CALCULATE(SUM(f_item_prices_snap[purchase_Price]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7d744729-4935-466e-8166-dca4aaef1b81

	measure 'Total Revenue of Category' = [Total Item Usage] * [Sale Prices]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 37b31e01-721a-4801-b3ad-b11115e471ca

	measure 'Weighted Average A' = ([Total Revenue of Category] - [Total Cost of Category]) / [Total Revenue of Category]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 45121fe8-020f-458f-8d4f-30a1b8683ca6

	measure 'Total Cost of Category' = [Total Item Usage] * [Average Cost]
		lineageTag: 18f0693d-aa8a-44cc-87e8-403b0425b9e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Weighted Average Final' = [Margin Percent] * [Quantity] / [Quantity]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c037b08f-d3bf-40bb-88db-1d4846a177b9

	partition 'Measures Table-4e9d625f-7e87-4cf8-9a13-1715b5302d88' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"." = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"."})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

